### ISSUE TITLE
Gmap.NET.Core Cross-Platform (Linux)

### ISSUE THREAD

**Issue by hellcoderGIT** [judero01col/GMap.NET#147]
I'm trying to move a project to .NET6 running on a Linux host (windows before).

Using only GMap.NET.Core but getting the following error when trying to create a map.

> System.TypeInitializationException: The type initializer for 'GMap.NET.GMaps' threw an exception. 2021-11-14T02:07:23.699326924Z: [INFO]         ---> System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
> 2021-11-14T02:07:23.699358524Z: [INFO]           at GMap.NET.Internals.NativeMethods.CreateSemaphore(IntPtr semaphoreAttributes, Int32 initialCount, Int32 maximumCount, String name)
> 2021-11-14T02:07:23.699375525Z: [INFO]           at GMap.NET.Internals.FastResourceLock..ctor()

Is Gmap.Net.Core supposed to be usable on Linux?

**Comment by JarradPosey** [comment]
I have run into a similar issue in my solution, @hellcoderGIT did you find a solution for this?

**Comment by hangdog78** [comment]
The same here =(

**Comment by hellcoderGIT** [comment]
I got it working by removing all the #if UseFastResourceLock code as well as Code related to "UseNativeSRWLock"

Not a proper fix but running it successfully on Linux with .NET6/7 for a while now.

FastReaderWriterLock.cs looks like this now:
`//#if !MONO
//#define UseFastResourceLock
//#endif
using System;
using System.Runtime.InteropServices;
using System.Threading;

namespace GMap.NET.Internals
{
    //#if !MONO
    //#endif

    /// <summary>
    ///     custom ReaderWriterLock
    ///     in Vista and later uses integrated Slim Reader/Writer (SRW) Lock
    ///     http://msdn.microsoft.com/en-us/library/aa904937(VS.85).aspx
    ///     http://msdn.microsoft.com/en-us/magazine/cc163405.aspx#S2
    /// </summary>
    public sealed class FastReaderWriterLock : IDisposable
    {
        //#if !MONO
        //        private static class NativeMethods
        //        {
        //            // Methods
        //            [DllImport("Kernel32", ExactSpelling = true)]
        //            internal static extern void AcquireSRWLockExclusive(ref IntPtr srw);

        //            [DllImport("Kernel32", ExactSpelling = true)]
        //            internal static extern void AcquireSRWLockShared(ref IntPtr srw);

        //            [DllImport("Kernel32", ExactSpelling = true)]
        //            internal static extern void InitializeSRWLock(out IntPtr srw);

        //            [DllImport("Kernel32", ExactSpelling = true)]
        //            internal static extern void ReleaseSRWLockExclusive(ref IntPtr srw);

        //            [DllImport("Kernel32", ExactSpelling = true)]
        //            internal static extern void ReleaseSRWLockShared(ref IntPtr srw);
        //        }

        //        IntPtr _lockSRW = IntPtr.Zero;

        //        public FastReaderWriterLock()
        //        {
        //            if (UseNativeSRWLock)
        //            {
        //                NativeMethods.InitializeSRWLock(out _lockSRW);
        //            }
        //            else
        //            {
        //#if UseFastResourceLock
        //                _pLock = new FastResourceLock();
        //#endif
        //            }
        //        }

        //#if UseFastResourceLock
        //        ~FastReaderWriterLock()
        //        {
        //            Dispose(false);
        //        }

        //        void Dispose(bool disposing)
        //        {
        //            if (_pLock != null)
        //            {
        //                _pLock.Dispose();
        //                _pLock = null;
        //            }
        //        }

        //        FastResourceLock _pLock;
        //#endif

        //        static readonly bool
        //            UseNativeSRWLock =
        //                Stuff.IsRunningOnVistaOrLater() &&
        //                IntPtr.Size == 4; // works only in 32-bit mode, any ideas on native 64-bit support? 

        //#endif

        //#if !UseFastResourceLock
        Int32 busy = 0;
        Int32 readCount = 0;
        //#endif

        public void AcquireReaderLock()
        {
            //#if !MONO
            //if (UseNativeSRWLock)
            //{
            //    NativeMethods.AcquireSRWLockShared(ref _lockSRW);
            //}
            //else
            //#endif
            //{
            //#if UseFastResourceLock
            //_pLock.AcquireShared();
            //#else
            Thread.BeginCriticalRegion();

            while (Interlocked.CompareExchange(ref busy, 1, 0) != 0)
            {
                Thread.Sleep(1);
            }

            Interlocked.Increment(ref readCount);

            // somehow this fix deadlock on heavy reads
            Thread.Sleep(0);
            Thread.Sleep(0);
            Thread.Sleep(0);
            Thread.Sleep(0);
            Thread.Sleep(0);
            Thread.Sleep(0);
            Thread.Sleep(0);

            Interlocked.Exchange(ref busy, 0);
            //#endif
            //}
        }

        public void ReleaseReaderLock()
        {
            //#if !MONO
            //            if (UseNativeSRWLock)
            //            {
            //                NativeMethods.ReleaseSRWLockShared(ref _lockSRW);
            //            }
            //            else
            //#endif
            //            {
            //#if UseFastResourceLock
            //                _pLock.ReleaseShared();
            //#else
            Interlocked.Decrement(ref readCount);
            Thread.EndCriticalRegion();
            //#endif
            //            }
        }

        public void AcquireWriterLock()
        {
            try
            {
                //#if !MONO
                //                if (UseNativeSRWLock)
                //                {
                //                    NativeMethods.AcquireSRWLockExclusive(ref _lockSRW);
                //                }
                //                else
                //#endif
                //                {
                //#if UseFastResourceLock
                //                    _pLock.AcquireExclusive();
                //#else
                Thread.BeginCriticalRegion();

                while (Interlocked.CompareExchange(ref busy, 1, 0) != 0)
                {
                    Thread.Sleep(1);
                }

                while (Interlocked.CompareExchange(ref readCount, 0, 0) != 0)
                {
                    Thread.Sleep(1);
                }
                //#endif
                // }
            }
            catch (Exception) { }
        }

        public void ReleaseWriterLock()
        {
            try
            {
                //#if !MONO
                //            if (UseNativeSRWLock)
                //            {
                //                NativeMethods.ReleaseSRWLockExclusive(ref _lockSRW);
                //            }
                //            else
                //#endif
                //            {
                //#if UseFastResourceLock
                //                _pLock.ReleaseExclusive();
                //#else
                Interlocked.Exchange(ref busy, 0);
                Thread.EndCriticalRegion();
                //#endif
                //          }
            }
            catch (Exception) { }
        }

        #region IDisposable Members

        public void Dispose()
        {
            //#if UseFastResourceLock
            //        Dispose(true);
            //        GC.SuppressFinalize(this);
            //#endif
        }

        #endregion
    }

}
`

**Comment by addriumruss** [comment]
Hi,  in MonoDevelop IDE, you can set compile variable MONO, and remove MONO_Disable, then compile again, all the DllImport statements would not be compiled, and I compile and run succeed in Ubuntu16.04. 

Sometimes in GMapControl.Paint(...) function, when the network is not very good, the Graphics.FillRectangle or the Graphics.reset_transform statements would fail and throw exceptions, resulting to exit of the control and the whole application. By adding try-catch in every paint functions these exceptions could be ignored, and the app then won't fail.

Just for reference, good luck.

**Comment by mshakurov** [comment]
This is so strange. 
Look at the list of available frameworks in nuget.org - there are listed many the .NET versions for which the GMap.NET.Core library is available. In fact, when accessing GMaps.Instance in Linux, the above error occurs.
It turns out that the authors lied on nuget.org, and this library does not work with the specified .NET versions.
And, most importantly, they do not answer this problem here.
